name: Download Songs from Website

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Enter the URL of the website to download songs from'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run download script
      run: python download_songs.py ${{ github.event.inputs.target_url }}

    - name: Upload downloaded songs as artifact
      uses: actions/upload-artifact@v3
      with:
        name: downloaded-songs
        path: downloads/
